# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5ba6d13c55ae16c34de2afcd8c1b821c607c12e31eb3c5c96e7884b17a20e7784190905f5cfce6702c245e12900a0ef4d5609005e593f811c52794457e8c9b

test:
  secret_key_base: 468451c362d16cdf28a3452d89609607355285ed5f1e3c766b96d7d236ad854edb8d5be323dee7a946934fcb83e3bb168d2ccd3b74c04d3fb31c9f7e4c15e999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
